export enum Icons {
  // Actions
  Add = 'mdi-plus',
  Remove = 'mdi-minus',
  Edit = 'mdi-pencil',
  Delete = 'mdi-delete',
  Save = 'mdi-content-save',
  Cancel = 'mdi-cancel',
  Search = 'mdi-magnify',
  Filter = 'mdi-filter-variant',
  Refresh = 'mdi-refresh',
  Upload = 'mdi-upload',
  Download = 'mdi-download',
  Share = 'mdi-share-variant',
  Settings = 'mdi-cog',
  Lock = 'mdi-lock',
  Unlock = 'mdi-lock-open',
  Check = 'mdi-check',
  Close = 'mdi-close',
  CloseOutline = 'mdi-close-circle-outline',
  Help = 'mdi-help-circle',
  Info = 'mdi-information',
  Warning = 'mdi-alert',
  WarningOutline = 'mdi-alert-outline',
  Error = 'mdi-alert-circle',
  Undo = 'mdi-undo',
  Redo = 'mdi-redo',
  Favorite = 'mdi-heart',
  Bookmark = 'mdi-bookmark',
  Copy = 'mdi-content-copy',
  Google = 'mdi-google',
  Logout = 'mdi-logout',

  // Navigation
  Home = 'mdi-home',
  Menu = 'mdi-menu',
  Back = 'mdi-arrow-left',
  Forward = 'mdi-arrow-right',
  ArrowUp = 'mdi-arrow-up',
  ArrowDown = 'mdi-arrow-down',
  Expand = 'mdi-arrow-expand',
  Collapse = 'mdi-arrow-collapse',
  ChevronUp = 'mdi-chevron-up',
  ChevronDown = 'mdi-chevron-down',
  ChevronLeft = 'mdi-chevron-left',
  ChevronRight = 'mdi-chevron-right',

  // Social
  Facebook = 'mdi-facebook',
  Twitter = 'mdi-twitter',
  Instagram = 'mdi-instagram',
  LinkedIn = 'mdi-linkedin',
  GitHub = 'mdi-github',
  YouTube = 'mdi-youtube',

  // Media
  Play = 'mdi-play',
  Pause = 'mdi-pause',
  Stop = 'mdi-stop',
  SkipNext = 'mdi-skip-next',
  SkipPrevious = 'mdi-skip-previous',
  VolumeUp = 'mdi-volume-high',
  VolumeSource = 'mdi-volume-source',
  VolumeDown = 'mdi-volume-low',
  VolumeMute = 'mdi-volume-off',
  Microphone = 'mdi-microphone',
  MicrophoneOff = 'mdi-microphone-off',

  // Devices
  Phone = 'mdi-phone',
  Tablet = 'mdi-tablet',
  Laptop = 'mdi-laptop',
  Desktop = 'mdi-monitor',
  Camera = 'mdi-camera',
  Printer = 'mdi-printer',
  Keyboard = 'mdi-keyboard',
  Mouse = 'mdi-mouse',
  Headphones = 'mdi-headphones',
  TV = 'mdi-television',

  // Files
  File = 'mdi-file',
  FileUpload = 'mdi-file-upload',
  FileDownload = 'mdi-file-download',
  Folder = 'mdi-folder',
  FolderOpen = 'mdi-folder-open',
  FolderPlus = 'mdi-folder-plus',
  FolderMinus = 'mdi-folder-minus',
  Document = 'mdi-file-document',
  Image = 'mdi-file-image',
  Video = 'mdi-file-video',
  Music = 'mdi-file-music',
  Zip = 'mdi-folder-zip',

  // User
  User = 'mdi-account',
  UserAdd = 'mdi-account-plus',
  UserRemove = 'mdi-account-minus',
  UserEdit = 'mdi-account-edit',
  UserGroup = 'mdi-account-group',
  UserCircle = 'mdi-account-circle',
  UserSettings = 'mdi-account-cog',

  // Location
  Map = 'mdi-map',
  Location = 'mdi-map-marker',
  LocationOff = 'mdi-map-marker-off',
  LocationAdd = 'mdi-map-marker-plus',
  LocationRemove = 'mdi-map-marker-minus',
  Compass = 'mdi-compass',

  // Shopping
  Cart = 'mdi-cart',
  CartAdd = 'mdi-cart-plus',
  CartRemove = 'mdi-cart-minus',
  CartCheck = 'mdi-cart-check',
  CartEmpty = 'mdi-cart-off',
  Tag = 'mdi-tag',
  Sale = 'mdi-sale',

  // Time & Date
  Clock = 'mdi-clock',
  Calendar = 'mdi-calendar',
  Alarm = 'mdi-alarm',
  Timer = 'mdi-timer',
  Stopwatch = 'mdi-stopwatch',
  Schedule = 'mdi-calendar-clock',

  // Weather
  Sun = 'mdi-weather-sunny',
  Moon = 'mdi-weather-night',
  Rain = 'mdi-weather-rainy',
  Cloud = 'mdi-cloud',
  CloudOutline = 'mdi-cloud-outline',
  Thunderstorm = 'mdi-weather-lightning',
  Snowflake = 'mdi-weather-snowy',

  // Misc
  Eye = 'mdi-eye',
  EyeOff = 'mdi-eye-off',
  Heart = 'mdi-heart',
  HeartOutline = 'mdi-heart-outline',
  Star = 'mdi-star',
  StarOutline = 'mdi-star-outline',
  StarHalf = 'mdi-star-half',
  Shield = 'mdi-shield',
  ShieldCheck = 'mdi-shield-check',
  CircleCheck = 'mdi-check-circle',
  ShieldOff = 'mdi-shield-off',
  Key = 'mdi-key',
  LockOpen = 'mdi-lock-open',
  LockClosed = 'mdi-lock',
  Lightbulb = 'mdi-lightbulb',
  Wrench = 'mdi-wrench',
  Hammer = 'mdi-hammer',
  Toolbox = 'mdi-toolbox',
  Puzzle = 'mdi-puzzle',
  Gift = 'mdi-gift',
  Fire = 'mdi-fire',
  Water = 'mdi-water',
  Shuffle = 'mdi-shuffle',
  InformationOutline = 'mdi-information-outline',
  MultipleMarkedOutline = 'mdi-checkbox-multiple-marked-outline',
  ViewCarouselIcon = 'mdi-view-carousel',
  TimeLineCheckOutline = 'mdi-timeline-check-outline',
}
