/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/quize/': RouteRecordInfo<'/quize/', '/quize', Record<never, never>, Record<never, never>>,
    '/quize/ViewMode': RouteRecordInfo<'/quize/ViewMode', '/quize/ViewMode', Record<never, never>, Record<never, never>>,
    '/topics/create': RouteRecordInfo<'/topics/create', '/topics/create', Record<never, never>, Record<never, never>>,
    '/topics/detail': RouteRecordInfo<'/topics/detail', '/topics/detail', Record<never, never>, Record<never, never>>,
    '/topics/update': RouteRecordInfo<'/topics/update', '/topics/update', Record<never, never>, Record<never, never>>,
  }
}
