/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/DictionaryCreate': RouteRecordInfo<'/DictionaryCreate', '/DictionaryCreate', Record<never, never>, Record<never, never>>,
    '/DictionaryDetail': RouteRecordInfo<'/DictionaryDetail', '/DictionaryDetail', Record<never, never>, Record<never, never>>,
    '/DictionaryUpdate': RouteRecordInfo<'/DictionaryUpdate', '/DictionaryUpdate', Record<never, never>, Record<never, never>>,
    '/HomePage': RouteRecordInfo<'/HomePage', '/HomePage', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/QuizePage': RouteRecordInfo<'/QuizePage', '/QuizePage', Record<never, never>, Record<never, never>>,
    '/WordViewerPage': RouteRecordInfo<'/WordViewerPage', '/WordViewerPage', Record<never, never>, Record<never, never>>,
  }
}
